# Generated by Django 3.2.6 on 2021-08-26 03:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('new_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thought',
            name='added_b7',
        ),
    ]
