# Generated by Django 3.2.6 on 2021-08-26 03:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('new_app', '0002_remove_thought_added_b7'),
    ]

    operations = [
        migrations.AddField(
            model_name='thought',
            name='posted_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='posted_thoughts', to='new_app.user'),
            preserve_default=False,
        ),
    ]
